---
name: zapata
channels:
  - conda-forge
  - ncar
dependencies:
  # Multi language support:
  - python=3.6
  - ipython
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - xarray
  - dask
  - pandas
  - cartopy
  - geocat-comp
  - geocat-datafiles
  - geocat-viz
  - ipywidgets
  - pygrib
  - tqdm
  - sphinx
  - seaborn
  - natsort
  - pudb
  - yapf
